package com.example.config


enum class SensorType {
    SMART_POWER_SOCKET_SENSOR,
    SMOKE_DETECTOR_SENSOR,
    MOTION_SENSOR,
    TEMPERATURE_SENSOR,
    SMART_LIGHT,
    HUMIDITY_SENSOR,
    SECURITY_SENSOR,
    DEVICE_STATE,
    ROOM_HEATING,
    VACUUM_CLEANER,
    HUMIDIFIER,
    COFFEE_MACHINE,
    AIR_CONDITIONER,
    TEAPOT
}

